---
  ### need to add squid proxy and update dnf config
  ### The internal servers need to install packages, but don't have access to the internet
  ### thus a Proxy on teh cliet is needed to be a bastion for the rest of the clients

- name: install and set up squid proxy for trhe Bastion/client
  when: inventory_hostname == bastion_host
  block:
    - name: Install squid proxy on bastion
      ansible.builtin.dnf:
        name: 
          - squid
        state: present

    ### to install packages on the servers behind the bastion/client I need to set dnf to use the bastion as a proxy.
    - name: define squi.conf
      ansible.builtin.template:
        src: templates/squid_conf.j2
        dest: /etc/squid/squid.conf
        force: true

    ### might need sudo for systemctl
    - name: Run command to enable squid
      ansible.builtin.command: sudo systemctl enable --now squid

    ### need to get the internal targe IP for the other internal servers
    - name: set bastion ip address for the other servers
      ansible.builtin.set_fact:
        bastion_ip: "{{ ansible_host }}"
        
  become: yes
  become_user: root
  ### Block Ende 


- name: block - edit dnf file on internal servers
  block: 
    ### to install packages on the servers behind the bastion/client I need to set dnf to use the bastion as a proxy.
    - name: Add proxy data to dnf.config to other servers
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf 
        line: "proxy=http://10.0.1.12:3128" 
      when: inventory_hostname != bastion_host
  become: yes
  become_user: root

### Test raw command and gain pyhton3 information as that became an issue with Ansible
- name: Get Python version
  ansible.builtin.shell: "echo $(python3 --version)" 
  register: python_ver

### Test raw command to find if the dnf.conf is changed correctly
- name: cat dnf.conf
  ansible.builtin.shell: "echo $(cat /etc/dnf/dnf.conf)" 
  register: dnf_conf
  become: yes
  become_user: root


## After updating python test to work.
- name: show python and dnf.conf version
  ansible.builtin.debug:
    msg:
      - "Python version: {{ python_ver.stdout}}" 
      - "dnf config file: {{ dnf_conf.stdout }}"
    

- name: Install common packages
  become: true
  become_user: root
  ansible.builtin.dnf:
    name: 
      - util-linux
      - xfsprogs
      - nano
      - openssh
      - pciutils
    state: present
  async: 300
  poll: 10