name: Lustre_builder
services:
  terraform:
    hostname: container-for-lustre
    volumes:
      - ./:/terraform_lustre
      - ~/.ssh/:/ssh
    working_dir: /terraform_lustre
    build:
      context: .
      dockerfile: dockerfile
