# Generated inventory for ansible from ec2 instances.

---
plugin: aws_ec2
aws_profile: default
regions:
  - eu-central-1
filters: 
  instance-state-name : running
  # tag:Project: LustreTest

# hostnames:
#   - ip-address
#   - dns-name

# keyed_groups:
#   - key: tags.Name
#     prefix: tag_Name_
#   - key: tags.Role
#     prefix: tag_Role_
#   - key: tags.Project
#     prefix: tag_Project_

compose:
  ansible_host: "{{ private_ip_address }}"
  public_ip_address: "{{ public_ip_address | default('') }}"
  