### Inventroy 

all:
  hosts:
    # lustre:
    lustre_client: 
      public_ip: 18.199.143.65 
      private_ip: 10.0.1.10

# OSS server
    lustre_oss: 
      private_ip: 10.0.1.11

# MGT server
    lustre_mgt: 
      private_ip: 10.0.1.12

