---
all:
  vars:
    ansible_ssh_private_key_file: /home/reseke/docker/Terraform_Lustre/.ssh/id.rsa
    host_key_checking: False
    ansible_user: ec2-user

  hosts:
    lustre_client: 
      ansible_host: 3.71.4.95
      public_ip: 3.71.4.95
      private_ip: 10.0.1.12

    lustre_oss:
      ansible_host: 10.0.1.11
      private_ip: 10.0.1.11
      ansible_ssh_common_args: "-o ProxyCommand=\"ssh -W %h:%p -i /home/reseke/.ssh/id_rsa ec2-user@3.67.196.143\""

    lustre_mgt:
      ansible_host: 10.0.1.10
      private_ip: 10.0.1.10
      ansible_ssh_common_args: "-o ProxyCommand=\"ssh -W %h:%p -i /home/reseke/.ssh/id_rsa ec2-user@3.67.196.143\""

