---
    ## Need to install a newer version of python to have ansible run properly
    ## Alma 8 version is only paython 3.6
- name: BLOCK Pyton upgrarde on Bastion
  when: inventory_hostname == bastion_host
  block:
  - name: Install Python 3.8
    raw: |
      sudo yum install -y python38 || dnf install -y python38
    become: true

  - name: Set Python interpreter for future tasks
    set_fact:
      ansible_python_interpreter: /usr/bin/python3.8  


### for the other systems a 
  - name: Load Python 3.8 ONLY
    raw: |
      sudo yum -y download --downloadonly python38
    become: true
  # end block    

- name: BLOCK Pyton upgrarde on other systems
  when: inventory_hostname != bastion_host
  block:
    - name: SCP from bastion to private hosts
      raw: >-
        scp -o StrictHostKeyChecking=no -i  /home/ec2-user/.ssh/lustretest /home/{{ ansible_user }}/python3*.rpm {{ ansible_user }}@{{ hostvars[inventory_hostname]['private_ip_address'] }}:/home/{{ ansible_user }} 
      delegate_to: "{{ bastion_host }}"


  # end block
  #always:

# - name: BLOCK on other servers, update python3.8
#   block:
#   - name:  python3.8 package
#     stat: 
#       path: ./python38
#     register: python_is_good
          
#   - name: install package
#     raw:
#       sudo yum localinstall ./python38
#       path
#   when: inventory_hostname is match('^ip-.*')

  
  ### exeption handing
  # rescue:

  # end block

  
...